{
 "title": "AirGradient Dashboard V3",
 "time": { "from": "2022-09-15T15:24:52.208Z", "to": "2022-09-16T02:26:51.784Z" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "sensor",
    "label": "Sensor",
    "query": "airgradient-tj-device2, airgradient-tj-office"
   }
  ]
 },
 "panels": [
  { "title": "Current Levels $sensor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "sensor" },
  {
   "title": "Current CO2 Concentration $sensor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rco2{job=~\"$sensor\"} < 10000 > -1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Temp (deg C) $sensor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "atmp{job=~\"$sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Humidity $sensor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rhum{job=~\"$sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current PM2.5 Air Pollution $sensor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pm02{job=~\"$sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "C02", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "C02 Concentration (ppm) Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "rco2{job=~\"$sensor\"} < 10000 > -1",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Temperature Over Time (°C)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "atmp{job=~\"$sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Humidity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "rhum{job=~\"$sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "PM2.5", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "PM2.5",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "pm02{job=~\"$sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}